---
- hosts: all
  remote_user: root
  tasks:
    - name: Update apt cache if older than 1d
      apt: update_cache=yes cache_valid_time=86400
      
    - name: Ensure unzip is present
      apt: pkg=unzip state=present

    - name: Ensure python-mysqldb is present
      apt: pkg=python-mysqldb state=present

    - name: Ensure taloLogger target dir exists and has proper permissions
      file: dest={{ tl_target_dir }} state=directory owner={{ tl_dir_owner }} mode=0755

    - name: Ensure taloLogger log dir exists and has proper permissions
      file: dest={{ tl_log_dir }} state=directory owner={{ tl_dir_owner }} mode=0755

    - name: Retrieve taloLogger installation package
      get_url: url={{ tl_download_URL }}/{{ tl_package }} dest={{ tl_target_dir }}

    - name: Retrieve taloLoggerGraph installation package
      get_url: url={{ tl_graph_download_URL }}/{{ tl_graph_package }} dest={{ tl_target_dir }}

    - name: Unzip taloLogger installation package
      unarchive: src={{ tl_target_dir }}/{{ tl_package }} dest={{ tl_target_dir }} creates={{ tl_target_dir }}/taloLogger copy=no

    - name: Insert MySQL root password to debconf configuration
      debconf:
        name: 'mysql-server'
        question: "{{ item }}"
        value: '{{ MYSQL_ROOT_PASS | quote }}'
        vtype: 'password'
      with_items:
        - mysql-server/root_password
        - mysql-server/root_password_again

    - name: Install datastore MySQL
      apt: pkg=mysql-server state=present
      when: IS_DATASTORE_MYSQL

    - name: Install talo MySQL user
      mysql_user: 
        login_user=root 
        login_password="{{ MYSQL_ROOT_PASS }}"
        name=talo 
        password=xxpassxx 
        priv=*.*:ALL,GRANT
        state=present

    - name: Create talo MySQL database
      mysql_db: 
        login_user=root
        login_password="{{ MYSQL_ROOT_PASS }}"
        name=talo state=present

    - name: Add MySQL as datastore in taloLogger.conf
      lineinfile:
        dest={{ tl_target_dir }}/taloLogger/taloLogger.conf
        regexp='^#?@DATASTORE=MYSQLDB:MYSQLDB'
        line='@DATASTORE=MYSQLDB:MYSQLDB'

    - name: Add uptime datasource to taloLogger.conf
      lineinfile: 
        dest={{ tl_target_dir }}/taloLogger/taloLogger.conf 
        regexp='^#?@DATASOURCE=SHELL:SHELL1'
        line='@DATASOURCE=SHELL:SHELL1'

    - name: Comment out dummy datasource in taloLogger.conf
      lineinfile:
        dest={{ tl_target_dir }}/taloLogger/taloLogger.conf
        regexp='^#?@DATASOURCE=DUMMY:DUMMY'
        line='#@DATASOURCE=DUMMY:DUMMY'

    - name: Comment out dummy measurement in taloLogger.conf
      lineinfile:
        dest={{ tl_target_dir }}/taloLogger/taloLogger.conf
        regexp='^#?@MEASURE = dummy:DUMMY.AnyDummyValue'
        line='#@MEASURE = dummy:DUMMY.AnyDummyValue'

    - name: Add uptime load measurement in taloLogger.conf
      lineinfile:
        dest={{ tl_target_dir }}/taloLogger/taloLogger.conf
        regexp='^#?\s?@MEASURE = systemload:SHELL1.value'
        line='@MEASURE = systemload:SHELL1.value'

